export const TERM_FILTER_OPTIONS = ['0 - 3 months', '3 - 6 months', '6 months - 1 year', 'more then 1 year'];
export const TEAM_FILTER_OPTIONS = ['1 team member', '2 - 4 team members', '4 - 10 team members', 'more then 10 team mambers'];
export const CATEGORY_FILTER_OPTIONS = ['Front-end', 'Back-end', 'Devops', 'UI/UX Designer', 'QA engineer', 'Admin support',
  'Customer service', 'Marketing', 'Accounting', 'Mobile dev', 'Database Administration', 'Copywriting', 'Team lead'];
export const BUDGET_MIN_VALUE = 100;
export const BUDGET_MAX_VALUE = 10000;
export const BUDGET_OPTIONS = {
  floor: 0,
  ceil: 100000,
  step: 100
};

export const TYPE_OPTIONS = ['fixed price', 'dedicated team', 'hourly rate'];

export const SKILLS_OPTIONS = [
  'Assign Passwords and Maintain Database Access',
  'Design Prototypes',
  'Documentation',
  'C',
  'C++',
  'CISC and RISC architecture',
  'HTML',
  'CSS',
  'CSS3',
  'Java sript',
  'Java',
  'Linux',
  'Memory management',
  'PCB layout review',
  'Python',
  'SQL',
  'UI/UX',
  'Unix',
  'XML',
  'AngularJs',
  'Angular 4',
  'Angular 2',
  'Angular 6',
  'Guru',
  'Git',
  'Bithub',
  'Bitbacket',
  'Jira',
  'Firebase',
  'AngularFire',
  'React',
  'React native',
  'Adobe Illustrator ',
  'Adobe Creative Cloud ',
  'Adobe Photoshop',
  'Art design',
  'AutoCAD',
  'HQL',
  'SASS',
  'SCSS',
  'Networking',
  'Systems administration',
  'Troubleshooting',
  'jQuery',
  'Unit testing',
  'gulp',
  'npm',
  'Graphic User Interfaces',
  'Portal Systems',
  'User Experience',
  'MVC',
  'Task Runners',
  'Microdata',
  'JavaScript Animation',
  'Templating Engines',
  'Command Line / CLI',
  'Integration Testing',
  'Web/Browser Security',

];
